[daiquiri]
docs_git_user = "deploy-token-user"
docs_git_pass = "deploy-token-pass"

[pgapp]
postgres_user = "daiquiri_app"
postgres_password = "daiquiri_app"

[pgdata]
postgres_user = "daiquiri_data"
postgres_password = "daiquiri_data"

[rabbitmq]
rabbitmq_user = "gaia"
rabbitmq_password = "password"
rabbitmq_default_user = "admin"
rabbitmq_default_pass = "admin"
