[daiquiri]
# docs_git_url = "https://oauth2:SECRET_ACCESS_TOKEN@gitlab.aip.de/django-daiquiri/cosmosim-content.git"

[pgapp]
postgres_user = "daiquiri_app"
postgres_password = "daiquiri_app"

[pgdata]
postgres_user = "daiquiri_data"
postgres_password = "daiquiri_data"

[rabbitmq]
rabbitmq_user = "gaia"
rabbitmq_password = "password"
rabbitmq_default_user = "admin"
rabbitmq_default_pass = "admin"
