version: "3.7"

services:
    daiquiri:
        build:
            context: ../../../docker/daiquiri
        container_name: dqdev-daiq
        depends_on:
            - pgapp
        links:
            - pgdata
            - wpdb
        restart: always

    pgapp:
        build:
            context: ../../../docker/pgapp
        container_name: dqdev-pgapp
        restart: always

    pgdata:
        build:
            context: ../../../docker/pgdata
        container_name: dqdev-pgdata
        restart: always

    wpdb:
        build:
            context: ../../../docker/wpdb
        container_name: dqdev-wpdb
        restart: always
